Repository LatteCode/Backend, pull requests merged in 2020-06, with the labels that each got.

#1 Add sql query module.
  public/javascripts/commnon.js
  routes/routes.js
Labels: DB, enhancement

#2 Adjust escape function to sql syntax
  public/javascripts/db.js
  routes/routes.js
Labels: DB, security

#3 License & README
  LICENSE
  README.md
Labels: documentation
